export type ActiveSurface =
  | 'chat'
  | 'notes'
  | 'canvas'
  | 'workrooms'
  | 'cowork'
  | 'projects'
  | 'artifacts'
  | 'code'
  | 'evaluate'
  | 'operate'
  | 'govern'
  | 'tune'
  | 'holographme'
  | 'marketplace'
  | 'computer'
